#!/bin/sh
DOMAIN=$(echo $QUTE_URL | awk -F/ '{print $3}' | awk -F. '{print $(NF-1)"."$NF}')
ROI=$(pass find "$DOMAIN" | tail -n +2 |  paste -sd '' | sed 's/└── //g' | sed 's/\s */\//g' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")
if [ -z "$ROI" ];
then
	exit 1
fi

ENTER=false
case $1 in
	pass)
		OUT=$(pass "$ROI" | head -n 1)
		ENTER=true
		;;
	user)
		OUT=$(pass "$ROI" | grep user | awk '{print $2}')
		;;
esac

echo enter-mode insert > $QUTE_FIFO
echo insert-text $OUT  > $QUTE_FIFO
if $ENTER
then
	echo  "fake-key <Return>" > $QUTE_FIFO
else

	echo "fake-key <Tab>" > $QUTE_FIFO
fi
echo enter-mode normal > $QUTE_FIFO
echo $OUT
